[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]


[dependencies]
forge-std = "1.9.3"
solady = "0.0.259"

[soldeer]
remappings_generate = true
remappings_regenerate = true 
remappings_version = false 
remappings_prefix = ""
remappings_location = "txt"
